// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/Shunsuke-ba/goat-server/mod/app/domain"
	"github.com/Shunsuke-ba/goat-server/mod/app/handler"
	"github.com/Shunsuke-ba/goat-server/mod/app/handler/sport_trader_handler"
	"github.com/Shunsuke-ba/goat-server/mod/app/usecase"
	"github.com/Shunsuke-ba/goat-server/mod/app/usecase/sport_trader_case"
)

// Injectors from wire.go:

func initApplication(ctx context.Context) AllRepository {
	health := domain.Health{}
	usecaseHealth := usecase.ProvideHealthCase(ctx, health)
	provideHealth := handler.ProvideHealthHandler(usecaseHealth)
	gameResults := sport_trader_case.ProvideGameResultsCase(ctx)
	provideGameResults := sport_trader_handler.ProvideGameResultsHandler(gameResults)
	gameSchedules := sport_trader_case.ProvideGameShedulesCase(ctx)
	provideGameSchedules := sport_trader_handler.ProvideGameSchedulesHandler(gameSchedules)
	headToHeads := sport_trader_case.ProvideHeadToHeadsCase(ctx)
	provideHeadToHeads := sport_trader_handler.ProvideHeadToHeadsHandler(headToHeads)
	allRepository := NewAllRepository(provideHealth, provideGameResults, provideGameSchedules, provideHeadToHeads)
	return allRepository
}
