// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/Shunsuke-ba/goat-server/mod/app"
	"github.com/Shunsuke-ba/goat-server/mod/app/domain"
	"github.com/Shunsuke-ba/goat-server/mod/app/handler"
	"github.com/Shunsuke-ba/goat-server/mod/app/usecase"
)

// Injectors from wire.go:

func initApplication(ctx context.Context) app.AllRepository {
	healthRepository := domain.HealthRepository{}
	health := usecase.ProvideHealthCase(ctx, healthRepository)
	provideHealth := handler.ProvideHealthHandler(health)
	allRepository := app.NewAllRepository(provideHealth)
	return allRepository
}
